
DROP TABLE IF EXISTS Music.SpotifyListens;
DROP TABLE IF EXISTS Music.Genre;
DROP TABLE IF EXISTS Music.Billboard;
DROP TABLE IF EXISTS Music.RecordLabel;
DROP TABLE IF EXISTS Music.Album;
DROP TABLE IF EXISTS Music.Artist;
DROP TABLE IF EXISTS Music.Song;